# Change these first
owner: tl-dr-filecoin # Your GitHub organization or username, where this repository lives
repo: site-status-monitoring # The name of this repository

sites:
  - name: TLDR Filecoin
    url: https://www.filecointldr.io
  - name: TLDR Filecoin Blog
    url: https://www.filecointldr.io/blog
  - name: TLDR Filecoin How to Stake FIL
    url: https://www.filecointldr.io/how-to-stake-filecoin
  - name: TLDR Filecoin How to Buy FIL
    url: https://www.filecointldr.io/how-to-buy-filecoin
  - name: TLDR Filecoin Views and Research
    url: https://www.filecointldr.io/views-and-research
  - name: TLDR Filecoin Terms & Conditions
    url: https://www.filecointldr.io/terms
  - name: TLDR Filecoin Privacy Policy
    url: https://filecointldr.io/privacy-policy
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /site-status-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TLDR Filecoin
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitoring page for TLDR Filecoin
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
